### PR TITLE
History component and call in home page on page

### PR DESCRIPTION
**Pull request by ChesterHuey**

### CODE REVIEW

**Comment by OrigamiStarz** [comment]
Hello Chester, great job on the history component so far! I especially like how you implemented a gradient background for the cards.

Could you make the following changes? Let me know if I need to clarify any of them. Sorry for making the list so long :')
- [ ] Put the `ViewHistory.tsx` inside of the `components` folder instead of the `History` folder
- [ ] Remove the `Add Post` and `Add User` buttons
  - [ ] You shouldn't need to track the number of users/posts
- [ ] Show all posts initially instead of having the user add them
- [ ] Squares instead of rectangles for users
- [ ] Should be more user friendly 
  - [ ] Some way to see all 10 temporary posts/users, like scrolling
  - [ ] Fix margin issue (currently inconsistent between viewing posts versus viewing users)
- [ ] A way to indicate which button is active (ex. make the `Post` button darker when posts are displayed)
- [ ] Each card should be linked to a post or user profile (use dummy data, especially for posts)
- [ ] Remove the like button for users
- [ ] Indicate if the user likes the post (use dummy data to see if the user liked the post)
  - [ ] Suggestion: filled heart for liked, unfilled heart for disliked
  - [ ] Also consider moving the number of likes below the heart icon
- [ ] Consider removing gradient background for users
- [ ] Inside `ViewHistory.tsx`, use a div with absolute positioning surrounding its contents (to make it easier to integrate into other pages)

**Comment by ChesterHuey** [comment]
Thanks for the suggestions. The buttons were there to see how it looked every time the user swiped, but that isn't very necessary. When clicking the user and the post the design isn't completed. I'll finish up implementing the user pages and then I'll use that design. Let me know if there are any other issues.

**Comment by ChesterHuey** [comment]
When clicked should the user and post show the same thing or different designs.

**Review by OrigamiStarz — CHANGES_REQUESTED** [review]
Good job so far! I'll approve it once you make these changes:
- [x] Delete History folder
- [ ] Center "View History" (`text-center`)
- [ ] Change `style={{ maxHeight: '350px' }}` into Tailwind (`max-h-[350px]`)
- [ ] Revert page.tsx back to the original state (to prevent merge conflicts)

**Review by OrigamiStarz — CHANGES_REQUESTED** [review]
One last thing, could you put the heading text ("View History") inside the container? I think the absolute positioning in the div surrounding the h1 (`<div className="absolute top-4 left-1/2 transform -translate-x-1/2">`) is messing it up. 
This is what I currently see when I test out the component:
Screenshot 2024-12-27 at 10 58 32 PM

**Review by OrigamiStarz — APPROVED** [review]

**Review by OrigamiStarz — APPROVED** [review]
Everything looks good! I'll go merge it with main.

**Pull request merged**
