### PR TITLE
Created messages page, configured web sockets, and added authentication handling to frontend

### PR DESCRIPTION
**Pull request by crebollarramirez**
# Messaging Feature Implementation

## Frontend
- **Messaging Page**:
  - Developed a functional messaging page allowing users to communicate in real-time.
  - Features a **"Recent Messages"** sidebar, currently listing all registered users (except the current user) as potential message recipients.
  - Includes a **chat log** where messages are displayed during conversations.
  - Messages are not saved yet due to pending database structuring.
  - Design closely follows the Figma prototype, with minor differences.
  - Added frontend authentication where users can login/register only with google OAuth.
  - Added where authenticated users making api requests also sends their session info letting the backend know they are authenticated. 

## Backend
- Configured **WebSocket** functionality to enable real-time messaging between users.
  - Utilizes user IDs to generate unique conversation IDs for each interaction.
- Updated backend logic to save registered users in the database.
  - The **"Recent Messages"** section on the frontend fetches this user list for displaying available recipients.
- Created a folder **models** that contains all Schemas which for now include Users and Message Schemas. 

### Additional Comments
Minor changes can be found in the _changed files_ of this PR.

### CODE REVIEW

**Comment by OrigamiStarz** [comment]
Hello Stezzy, great job on the messages page.

Here are some suggestions (mainly UX, none are critical to the functionality):
- [ ] When a new message is sent, both users should automatically scroll down to the latest message, if they haven't scrolled back up (similar to Discord)
- [ ] Make the edges of the component rounded
  - [ ] This is only a problem when there is at least 1 page worth of messages
- [ ] Fix the font colors for the blue messages for the words `You` and `date time`
- [ ] Make the page more responsive for mobile specifically
  - [ ] The sidebar becomes cramped, easiest fix is to leave the PFP only, but probably best to come up with something else in the long run
- [ ] Have a way to indicate the active user in the side bar (ex. more gray)
- [ ] Have a preview of the last sent message in the side bar (I presume this will be implemented after the messages database is set up?)

Let me know if you have any questions or need me to clarify anything.

**Comment by crebollarramirez** [comment]
Since our original design didn't include data, time, and sender indicator, i just removed it. Also for now, I think it would be better to worry about responsive design at the end so we can focus more on the main features of our project. Once the database is setup for messages, we can implement the most recent message of each user in the recent messages section.

**Review by OrigamiStarz — APPROVED** [review]
The FE is good enough for MVP, you're free to merge after Ryan also approves.

**Review by theryanfo — APPROVED** [review]
Looks good. Im also currently nearly finished with integrating the MongoDB database. I have  a more detailed User.ts that we can talk about merging later and right now it successfully gets and posts to the database. It should be simple to complete the messages and posts since it follows the same template

**Pull request merged**
